version: 2.1
orbs:
  unity: game-ci/unity@1.4.0
workflows:
  test-build-with-executors:
    jobs:
# Windows #########################################
      - unity/test:
          context: unity
          executor:
            editor_version: 2019.3.13f1
            name: unity/ubuntu
            resource_class: medium
            target_platform: windows-mono
          name: test-windows
          project-path: jade_gitlab